#!/usr/bin/env bash
# Update package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Start Nginx
sudo service nginx start

# Enable Nginx to start on boot
sudo systemctl enable nginx

# Create a custom HTML page
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart

# Allow HTTP traffic through the firewall (if UFW is enabled)
sudo ufw allow 'Nginx Full'
