#!/usr/bin/env bash
# Script to install nginx and configure it to redirect to another page when accessing the /redirect_me page.
sudo apt update -y
sudo apt install nginx -y

# Create directories and files for custom pages
sudo mkdir -p /var/www/html
sudo mkdir -p /etc/nginx/html
sudo touch /var/www/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Store configuration content
new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
            internal;
            root /etc/nginx/html;
        }
}
"

# Write new configuration to the default site config
echo "$new_config" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
